// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Load .env.local first, then .env. dotenv never overrides an already-set
// var, so precedence is: real environment > .env.local > .env (local
// overrides base, and a real deploy-time env var still wins over both).
config({ path: ".env.local" });
config();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Used by `prisma migrate diff --from-migrations` (the db:check-drift
    // script) to replay tracked migrations into a throwaway database.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
